export const SERVICE_OFFERINGS = [
  {
    id: "website-development",
    title: "Website development",
    flowLabel: "Websites that work",
    description: "A clear first impression, a fast experience, and a straightforward path from visitor to enquiry.",
    detail: "Business websites, landing pages, and online stores with responsive layouts, content management, and the integrations your customer journey needs.",
    deliverables: ["Business websites", "E-commerce", "Landing pages"],
  },
  {
    id: "saas-development",
    title: "SaaS & web applications",
    flowLabel: "Ideas into products",
    description: "Turn a product idea or an everyday business workflow into software people can actually use.",
    detail: "From a focused MVP to a custom application: user roles, subscription flows, dashboards, APIs, and a technical foundation that supports the next release.",
    deliverables: ["Product MVPs", "Custom dashboards", "API integrations"],
  },
  {
    id: "ai-automation",
    title: "AI automation",
    flowLabel: "Less repetitive work",
    description: "Connect your tools and use AI to help with the repetitive work between them.",
    detail: "Automate lead routing, document processing, customer follow-ups, and internal handoffs, with clear review points and a way for your team to take over.",
    deliverables: ["Workflow automation", "AI assistants", "CRM integrations"],
  },
  {
    id: "generative-ai",
    title: "Generative AI",
    flowLabel: "AI with a purpose",
    description: "Put language models to work inside a useful product, grounded in your content and processes.",
    detail: "Knowledge assistants, document search, content drafting, and LLM integrations with source references, evaluation, and human review shaped around the use case.",
    deliverables: ["Knowledge assistants", "Content workflows", "LLM integrations"],
  },
  {
    id: "seo",
    title: "Search engine optimization",
    flowLabel: "Make discovery easier",
    description: "Help search engines understand your website and help the right visitors find what they need.",
    detail: "Technical SEO, site structure, service-page content, metadata, and search measurement, with priorities based on the site's current condition and audience.",
    deliverables: ["Technical SEO", "On-page SEO", "Search strategy"],
  },
  {
    id: "digital-marketing",
    title: "Digital marketing",
    flowLabel: "Turn attention into action",
    description: "Bring your message, campaigns, and landing pages together around a clear business goal.",
    detail: "Campaign planning, content direction, email journeys, and conversion tracking that connect marketing activity with a useful next step for your audience.",
    deliverables: ["Campaign strategy", "Content & email", "Conversion tracking"],
  },
] as const
